const Emojis = require("../stats/emojis");

module.exports = {
    EMOJIS: {
        Leaderboard_1:  "<:lb_10:1277620451681767515>",
        Leaderboard_2:  "<:lb_9:1277620442332532848>",
        Leaderboard_3:  "<:lb_8:1277620415308632064>",
        Leaderboard_4:  "<:lb_7:1277620392998998036>",
        Leaderboard_5:  "<:lb_6:1277620381464924291>",
        Leaderboard_6:  "<:lb_5:1277620363869687889>",
        Leaderboard_7:  "<:lb_4:1277620354789015583>",
        Leaderboard_8:  "<:lb_3:1277619409468260383>",
        Leaderboard_9:  "<:lb_2:1277619392384864366>",
        Leaderboard_10: "<:lb_1:1277619355378520085>",

        Upgrade: "<:upgrade:1386092194980429855>",
        BrokenPickaxe: "<:BrokenPickaxe:1387913610805903592>",

        Candy: "<:Candy:1411739676041281657>",
        Skull: "<:Skull:1418777536845975643>",
        CandyBasket: "<:CandyBasket:1411878280486846558>",
        Cookie: "<:Cookie:1417811796252819466>",

        Coin: "<:Coin:>1489783746835120329",
        Gems: "<:Gems:1417581211446018171>",

        Gambled: "<:Gambled:1418791109676630017>",

        Cash1: "<:cash:1277627351869558804>",
        Cash5: "<:cash5:1388669590862696541>",

        UI_Cross: "<:ui_cross:1399887525522178220>",
        UI_Warn: "<:ui_warn:1399887498460528790>",
        UI_Plus: "<:ui_plus:1399887474590875929>"
    },

    COLORS: {
        pink: 0xFF69B4,
        purple: 0x800080,
        blue: 0x3498db,
        green: 0x2ecc71,
        orange: 0xe67e22,
        red: 0xe74c3c,
        yellow: 0xf1c40f,
        teal: 0x008080,
        cyan: 0x00ffff,
        indigo: 0x4b0082,
        lime: 0x00ff00,
        brown: 0x8B4513,
        magenta: 0xFF00FF,
        olive: 0x808000,
        navy: 0x000080,
        maroon: 0x800000,
        lavender: 0xE6E6FA,
        peach: 0xFFDAB9,
        coral: 0xFF7F50,
        gold: 0xFFD700,
        silver: 0xC0C0C0,
        plum: 0xDDA0DD,
        turquoise: 0x40E0D0,
        chocolate: 0xD2691E,
        crimson: 0xDC143C,
        forestGreen: 0x228B22,
        midnightBlue: 0x191970,
        darkSlateGray: 0x2F4F4F,
        darkCyan: 0x008B8B,
        darkViolet: 0x9400D3,
        darkOrange: 0xFF8C00,
        darkOliveGreen: 0x556B2F,
        darkGoldenrod: 0xB8860B,
        darkMagenta: 0x8B008B,
        darkTurquoise: 0x00CED1,
        darkRed: 0x8B0000,
        darkBlue: 0x00008B,
        darkGreen: 0x006400,
        darkYellow: 0x808000,
        darkPink: 0x9D00FF,
        darkBrown: 0x5C4033,
    },

    WORK_COMMANDS: {
        Fail: [
            "You ringed and no one opened.",
            "You ringed and where given an apple.",
            "You knocked, but nobody was home.",
            "A bird stole your candy before you could grab it.",
            "Someone ignored your ring. No candy for you.",
            "The door opened, but it was just a cat. No candy.",
            "You knocked but only heard laughter inside.",
            "A gust of wind blew your candy bag away.",
            "Someone told you 'Try again tomorrow!'",
            "You tripped and your candy fell into a puddle.",
            "You got lost on your way and came back empty-handed.",
            "The door opened, but they gave you a broom instead of candy.",
            "A tiny gnome challenged you to a dance battle instead of giving candy.",
            "The door opened and a mime silently judged you. No candy.",
            "A raccoon stole your shoes and left a note saying 'Better luck next time.'",
            "You opened the door but stepped into a parallel dimension with no candy.",
            "A random llama appeared and spit on your candy bag. Sad!",
            "Someone handed you a banana and said 'Close enough.'",
            "You got scared by a floating pumpkin and dropped all your candy.",
            "You slipped on a curb and dropped the candy you just earned.",
            "You knocked, but a skeleton answered and said, 'No candy, just bones!'",
            "A witch cackled and turned your candy into a carrot. Yuck!",
            "You rang the bell, but a swarm of bats flew out instead of candy.",
            "A grumpy goblin slammed the door and yelled, 'Go eat spinach!'",
            "Your candy bag got caught in a spider web. No treats for you!",
            "A talking pumpkin told you, 'Come back when you're scarier.'",
            "You reached for candy, but a trapdoor opened, and you fell into a pile of leaves.",
            "A ghost dog barked and chased you away before you got any candy.",
            "You knocked, but the house was a hologram. No candy, just tricks!",
            "A sneaky gremlin swapped your candy for a bag of pebbles.",
            `Ouch. The bowl was empty… maybe next door has ${Emojis.Candy} candy.`,
            `The shadows cackle and snatch your loot. No ${Emojis.Candy} candy this time.`,
            `Trick’s on you! A ghostly gust swiped your ${Emojis.Candy} candy chances.`,
            `Not every door hides sweetness… just cobwebs and a sassy ${Emojis.Skull} grin.`,
            `Candy? Nope. Just a spooky ${Emojis.Skull} and a bag full of regret.`,
            `A cackling crow swooped down and nabbed your ${Emojis.Candy} candy haul!`,
            `You knocked, but a poltergeist slammed the door with a mocking ${Emojis.Skull} smirk.`,
            `A mischievous fairy swapped your candy for a handful of glitter. Sparkly, but sad!`,
            `The door creaked open, but a zombie offered you brains instead of ${Emojis.Candy} candy.`,
            `A haunted mailbox ate your candy bag and burped a ${Emojis.Skull} cloud.`,
            `You tripped over a cursed root, and your ${Emojis.Candy} candy rolled into a storm drain.`,
            `A troll under the porch demanded a riddle answer. You failed, no ${Emojis.Candy} candy!`,
            `You rang the bell, but a ghostly hand pushed you back with a ${Emojis.Skull} chuckle.`,
            `A witch’s cat hissed and knocked your candy bag into a cauldron. No ${Emojis.Candy} treats!`,
            `You reached for candy, but a magic mirror showed you eating broccoli instead.`,
            `A dancing scarecrow stole your ${Emojis.Candy} candy and moonwalked away!`,
            `You knocked, but a sentient toaster popped up and flung burnt toast at you. No ${Emojis.Candy}!`,
            `A rogue jack-in-the-box sprang out and scared your ${Emojis.Candy} candy into a sewer grate.`,
            `You opened the door, but a talking sock puppet demanded your ${Emojis.Candy} as payment.`,
            `A swarm of glittery moths ate your ${Emojis.Candy} candy bag and left a ${Emojis.Skull} note.`,
            `You tripped on a rogue candy corn and faceplanted into a pile of leaves. No ${Emojis.Candy}!`,
            `A grumpy leprechaun offered you gold coins but snatched your ${Emojis.Candy} candy instead.`,
            `You rang the bell, but a sentient pumpkin pie sliced itself and offered you crumbs. No ${Emojis.Candy}!`,
            `A ghostly vacuum cleaner sucked up your ${Emojis.Candy} candy and wheezed a ${Emojis.Skull} laugh.`,
            `You knocked, but a disco ball spun out and hypnotized you into forgetting ${Emojis.Candy} candy.`,
            `A ${Emojis.CandyCorn} avalanche buried your candy bag under a pile of kernels!`,
            `You knocked, but a spectral chicken clucked and pecked your ${Emojis.Candy} candy away.`,
            `A cursed vending machine ate your ${Emojis.Candy} candy and spat out a ${Emojis.Skull} sticker.`,
            `You tripped over a possessed skateboard, and your ${Emojis.Candy} candy flew into the void.`,
            `A giggling gremlin swapped your ${Emojis.Candy} for a ${Emojis.CandyCorn} that’s suspiciously stale.`,
            `A haunted teapot whistled and steamed your ${Emojis.Candy} candy into oblivion.`,
            `You rang the bell, but a ${Emojis.CandyCorn} golem roared and scared you empty-handed.`,
            `A ghostly barber snipped your candy bag and left you with a ${Emojis.Skull} haircut.`,
            `You reached for ${Emojis.Candy}, but a magic carpet zoomed off with your treats!`,
            `A rogue ${Emojis.CandyCorn} rolled away, leading your ${Emojis.Candy} candy into a trap.`
        ],

        Response: [
            `You were given ${Emojis.Candy} {amount} candy!`,
            `A rich person opened and gave you ${Emojis.Candy} {amount} candy.`,
            `You ran around and found ${Emojis.Candy} {amount} on the ground.`,
            `You got lucky and received ${Emojis.Candy} {amount} candy!`,
            `A kind stranger handed you ${Emojis.Candy} {amount} candy.`,
            `A mysterious stranger gave you ${Emojis.Candy} {amount} candy, you should follow him.`,
            `You trained a crow and it came with ${Emojis.Candy} {amount} candy back.`,
            `A clown dropped ${Emojis.Candy} {amount} candy in front of you!`,
            `Someone shouted 'Trick or treat!' and handed you ${Emojis.Candy} {amount} candy.`,
            `You discovered a hidden stash and grabbed ${Emojis.Candy} {amount} candy.`,
            `A wizard appeared and gave you ${Emojis.Candy} {amount} candy as a gift.`,
            `You completed a small quest and earned ${Emojis.Candy} {amount} candy!`,
            `A tiny alien beamed down and handed you ${Emojis.Candy} {amount} candy from space.`,
            `A squirrel politely handed you ${Emojis.Candy} {amount} candy, then ran away.`,
            `You opened a treasure chest and found ${Emojis.Candy} {amount} candy... and a tiny rubber duck.`,
            `A mysterious fog appeared and left ${Emojis.Candy} {amount} candy at your feet.`,
            `You followed a rainbow and found ${Emojis.Candy} {amount} candy at the end.`,
            `A friendly ghost handed you ${Emojis.Candy} {amount} candy and winked.`,
            `A dancing skeleton tossed you ${Emojis.Candy} {amount} candy for your cool moves!`,
            `You solved a riddle and a magical owl dropped ${Emojis.Candy} {amount} candy in your bag!`,
            `A friendly vampire shared ${Emojis.Candy} {amount} candy, but warned it’s ‘fang-tastic’!`,
            `You high-fived a werewolf and got ${Emojis.Candy} {amount} candy as a reward!`,
            `A pirate ghost sailed by and left ${Emojis.Candy} {amount} candy in your bucket!`,
            `You found a glowing jack-o’-lantern with ${Emojis.Candy} {amount} candy inside!`,
            `A cheerful witch brewed you a potion and added ${Emojis.Candy} {amount} candy as a bonus!`,
            `You outran a zombie and found ${Emojis.Candy} {amount} candy in its hiding spot!`,
            `A magical cat purred and dropped ${Emojis.Candy} {amount} candy from its sparkly collar!`,
            `You sang a spooky song and earned ${Emojis.Candy} {amount} candy from a ghostly choir!`,
            `Sweet! You snatched ${Emojis.Candy} {amount} candy like a true trick-or-treater.`,
            `Sugar rush unlocked! ${Emojis.Candy} {amount} candy fattens your spooky stash.`,
            `The spirits smile and drop ${Emojis.Candy} {amount} candy in your haunted bag.`,
            `Jack-o’-lantern approved! You scored ${Emojis.Candy} {amount} candy with flair!`,
            `Your pockets overflow with ${Emojis.Candy} {amount} candy. Keep haunting, champ!`,
            `A mischievous imp tossed you ${Emojis.Candy} {amount} candy for outsmarting it!`,
            `You moonwalked past a ghoul and snagged ${Emojis.Candy} {amount} candy!`,
            `A enchanted broom swept ${Emojis.Candy} {amount} candy right into your bag!`,
            `You dodged a flying bat and found ${Emojis.Candy} {amount} candy in its nest!`,
            `A giggling goblin traded you ${Emojis.Candy} {amount} candy for a silly face!`,
            `A haunted candelabra lit up and dropped ${Emojis.Candy} {amount} candy at your feet!`,
            `You outwitted a sphinx and earned ${Emojis.Candy} {amount} candy as a prize!`,
            `A friendly banshee wailed a tune and gifted you ${Emojis.Candy} {amount} candy!`,
            `You found a secret trapdoor with ${Emojis.Candy} {amount} candy hidden inside!`,
            `A cosmic jack-o’-lantern beamed ${Emojis.Candy} {amount} candy from another dimension!`,
            `You bribed a grumpy troll with a dance and got ${Emojis.Candy} {amount} candy!`,
            `A sneaky raccoon dropped ${Emojis.Candy} {amount} candy after you chased it!`,
            `You tickled a skeleton, and it coughed up ${Emojis.Candy} {amount} candy in laughter!`,
            `A haunted vending machine spat out ${Emojis.Candy} {amount} candy for free!`,
            `You outsmarted a talking scarecrow and nabbed ${Emojis.Candy} {amount} candy!`,
            `A friendly poltergeist juggled ${Emojis.Candy} {amount} candy right into your bag!`,
            `You found a cursed candy cane that turned into ${Emojis.Candy} {amount} candy!`,
            `A werewolf DJ spun a track and tossed you ${Emojis.Candy} {amount} candy!`,
            `You dodged a rolling pumpkin and found ${Emojis.Candy} {amount} candy in its path!`,
            `A ghostly baker handed you ${Emojis.Candy} {amount} candy from a spectral oven!`,
            `A ${Emojis.CandyCorn} golem crumbled and revealed ${Emojis.Candy} {amount} candy inside!`,
            `You outran a ${Emojis.CandyCorn} tsunami and grabbed ${Emojis.Candy} {amount} candy!`,
            `A spectral squirrel chucked ${Emojis.Candy} {amount} candy at you from a haunted tree!`,
            `You danced with a ${Emojis.CandyCorn} witch and earned ${Emojis.Candy} {amount} candy!`,
            `A possessed piñata burst open, showering you with ${Emojis.Candy} {amount} candy!`,
            `You high-fived a ${Emojis.CandyCorn} ghost and got ${Emojis.Candy} {amount} candy!`,
            `A zombie chef baked you ${Emojis.Candy} {amount} candy in a creepy oven!`,
            `You found a ${Emojis.CandyCorn} treasure map leading to ${Emojis.Candy} {amount} candy!`,
            `A mischievous ${Emojis.CandyCorn} gremlin tripped but dropped ${Emojis.Candy} {amount} candy!`,
            `You rode a haunted rollercoaster and found ${Emojis.Candy} {amount} candy at the end!`
        ],
    },
    RPS: [
        "a flip-flop",
        "a wet sock",
        "a traffic cone",
        "a toaster",
        "grandma’s slipper",
        "a rubber duck",
        "the IRS",
        "a pineapple pizza",
        "a haunted Roomba",
        "your internet provider",
        "an angry goose",
        "Shrek",
        "a Windows update",
        "a VHS tape",
        "a cursed fidget spinner",
        "a spoon (just a spoon)",
        "the concept of taxes",
        "a TikTok dance",
        "Elon Musk’s flamethrower",
        "a Minecraft dirt block",
        "a squeaky dog toy",
        "your last brain cell",
        "a Nokia 3310",
        "a banana peel",
        "a Discord mod",
        "a Fortnite default dance",
        "a moldy sandwich",
        "an Uno reverse card",
        "a suspicious candy corn",
        "a flip phone",
        "a shopping cart",
        "a screaming goat",
        "a Game Boy Color",
        "an expired coupon",
        "a cursed AI response",
        "a haunted kazoo",
        "a participation trophy"
    ]
}
